### ISSUE TITLE
Indicatif's progress bar panics if template is too large

### ISSUE THREAD

**Issue by nbigaouette-eai** [mitsuhiko/indicatif#45]
If I set a template that is too large for the terminal window, the `inc()` call panics.

Minimal example:
```rust
extern crate indicatif;
use indicatif::ProgressBar;

fn main() {
    let pb = ProgressBar::new(100);
    pb.set_style(indicatif::ProgressStyle::default_bar()
            .template("{wide_bar:.cyan/blue} {pos:>6}/{len:6} ************************************************************************************************************************************************************************************"));
    for i in 0..100 {
        pb.inc(1);
        std::thread::sleep_ms(10);
    }
    pb.finish();
}
```

Backtrace:
```
 -> echo $COLUMNS && cargo run
143
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/tind`
thread 'main' panicked at 'attempt to subtract with overflow', /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/indicatif-0.9.0/src/progress.rs:309:37
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::begin_panic
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::try::do_call
             at libstd/panicking.rs:521
   7: std::panicking::try::do_call
             at libstd/panicking.rs:497
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at libcore/panicking.rs:71
   9: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at libcore/panicking.rs:51
  10: indicatif::progress::ProgressStyle::format_state
             at /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/indicatif-0.9.0/src/progress.rs:309
  11: indicatif::progress::draw_state
             at /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/indicatif-0.9.0/src/progress.rs:666
  12: indicatif::progress::ProgressBar::draw
             at /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/indicatif-0.9.0/src/progress.rs:652
  13: indicatif::progress::ProgressBar::update_and_draw
             at /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/indicatif-0.9.0/src/progress.rs:648
  14: indicatif::progress::ProgressState::eta
             at /Users/nbigaouette/.cargo/registry/src/github.com-1ecc6299db9ec823/indicatif-0.9.0/src/progress.rs:534
  15: tind::main
             at src/main.rs:9
  16: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  17: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  18: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  19: rust_panic
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  20: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  21: tind::main
```

Note that the above panic happens for a terminal window of width 143 columns.

**Comment by mitsuhiko** [comment]
This is fixed now.
